export const RESTAURANTS_FETCH_REQUEST = 'RESTAURANTS_FETCH_REQUEST';
export const RESTAURANTS_FETCH_SUCCESS = 'RESTAURANTS_FETCH_SUCCESS';
export const RESTAURANTS_FETCH_FAILURE = 'RESTAURANTS_FETCH_FAILURE';
export const ACTIVE_RESTAURANT_SET = 'ACTIVE_RESTAURANT_SET';
export const ACTIVE_RESTAURANT_CLEAR = 'ACTIVE_RESTAURANT_CLEAR';
export const ACTIVE_VIEW_CHANGE = 'ACTIVE_VIEW_CHANGE';